import React, { useEffect, useMemo, useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faPlus, faArrowLeft, faDownload, faFileMedical, faTrash, faPlay, faList, faChevronDown, faChevronUp
} from '@fortawesome/free-solid-svg-icons';
import { api } from '../lib/api';
import { useLanguage } from '../context/LanguageContext';
import '../CSS/Cases.css';
import mascotThinking from '../Assets/mascot_thinking.png';
import mascotHappyResult from '../Assets/mascot_happy_result.png';

const answerLetters = ['A', 'B', 'C', 'D', 'E'];
const emptyForm = { child_name: '', child_dob: '', brief: '' };

const emptyQchat = {
  child_sex: '', child_ethnicity: '', jaundice: '', family_asd: '',
  A1: '', A2: '', A3: '', A4: '', A5: '', A6: '', A7: '', A8: '', A9: '', A10: ''
};

const Cases = () => {
  const { t, language } = useLanguage();
  const [view, setView] = useState('list');
  const [cases, setCases] = useState([]);
  const [form, setForm] = useState(emptyForm);
  const [activeCase, setActiveCase] = useState(null);
  const [reports, setReports] = useState([]);
  const [gameScores, setGameScores] = useState([]);
  const [currentReport, setCurrentReport] = useState(null);
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');
  const [qchat, setQchat] = useState(emptyQchat);

  const [assessmentStep, setAssessmentStep] = useState('image');
  const [faceImage, setFaceImage] = useState(null);
  const [imagePreview, setImagePreview] = useState('');
  const [imageChecked, setImageChecked] = useState(false);

  const [displayCount, setDisplayCount] = useState(6);

  const questionTexts = {
    1: t.q1, 2: t.q2, 3: t.q3, 4: t.q4, 5: t.q5,
    6: t.q6, 7: t.q7, 8: t.q8, 9: t.q9, 10: t.q10,
  };

  const options = {
    1: [t.always, t.usually, t.sometimes, t.rarely, t.never],
    2: [t.veryEasy, t.quiteEasy, t.quiteDifficult, t.veryDifficult, t.impossible],
    3: [t.manyTimesDay, t.fewTimesDay, t.fewTimesWeek, t.lessThanOnceWeek, t.never],
    4: [t.manyTimesDay, t.fewTimesDay, t.fewTimesWeek, t.lessThanOnceWeek, t.never],
    5: [t.manyTimesDay, t.fewTimesDay, t.fewTimesWeek, t.lessThanOnceWeek, t.never],
    6: [t.manyTimesDay, t.fewTimesDay, t.fewTimesWeek, t.lessThanOnceWeek, t.never],
    7: [t.always, t.usually, t.sometimes, t.rarely, t.never],
    8: [t.veryTypical, t.quiteTypical, t.slightlyUnusual, t.veryUnusual, t.doesntSpeak],
    9: [t.manyTimesDay, t.fewTimesDay, t.fewTimesWeek, t.lessThanOnceWeek, t.never],
    10: [t.manyTimesDay, t.fewTimesDay, t.fewTimesWeek, t.lessThanOnceWeek, t.never]
  };

  const translateReportToArabic = (englishText) => {
    if (!englishText) return '';
    let translated = englishText;

    const allMaps = {
      'Auto-Ism Final Report for': t.autoIsmFinalReportFor || 'التقرير النهائي من Auto-Ism لـ',
      'High risk': t.highRiskAr || 'خطر مرتفع',
      'Low risk': t.lowRiskAr || 'خطر منخفض',
      'Moderate risk': t.moderateRiskAr || 'خطر متوسط',
      'Risk Level': t.riskLevelAr || 'مستوى الخطر',
      'Q-CHAT Score': t.qchatScoreAr || 'درجة Q-CHAT',
      'Facial Analysis Score': t.facialAnalysisScoreAr || 'درجة تحليل الوجه',
      'Combined Risk Score': t.combinedRiskScoreAr || 'درجة المخاطر المجمعة',
      'Based on the analysis': t.basedOnAnalysisAr || 'بناءً على التحليل',
      'The results indicate': t.resultsIndicateAr || 'تشير النتائج إلى',
      'consult a specialist': t.consultSpecialistAr || 'استشارة أخصائي',
      'monitor development': t.monitorDevelopmentAr || 'مراقبة التطور',
      'early intervention': t.earlyInterventionAr || 'التدخل المبكر',
      'Please note': t.pleaseNoteAr || 'يرجى الملاحظة',
      'This is not a medical diagnosis': t.notMedicalDiagnosisAr || 'هذا ليس تشخيصاً طبياً',
      'For further evaluation': t.forFurtherEvaluationAr || 'للتقييم الإضافي',
      'Question responses': t.questionResponses || 'إجابات الأسئلة',
      'Weighting used': t.weightingUsed || 'الأوزان المستخدمة',
      'Q-CHAT weight': t.qchatWeight || 'وزن Q-CHAT',
      'Facial image weight': t.facialWeight || 'وزن الصورة',
      'No autism likelihood detected': t.noAutismLikelihoodDetected || 'لم يتم اكتشاف احتمالية التوحد',
      'Low autism likelihood': t.lowAutismLikelihood || 'احتمالية توحد منخفضة',
      'Autism likelihood detected': t.autismLikelihoodDetected || 'تم اكتشاف احتمالية التوحد',
      'Final assessment:': 'التقييم النهائي:',
      'Case ID': t.caseId || 'رقم الحالة',
      'Report ID': t.reportId || 'رقم التقرير',
      'Date': t.date || 'التاريخ',
      'Assessment Results': t.assessmentResults || 'نتائج التقييم',
      'Detailed Analysis': t.detailedAnalysis || 'تحليل مفصل',
      'Generated by': t.generatedBy || 'تم الإنشاء بواسطة',
      'Q-CHAT risk': t.qchatRisk || 'خطر Q-CHAT',
      'Facial image risk': t.facialImageRisk || 'خطر صورة الوجه',
      'Facial risk': t.facialRisk || 'خطر الوجه',
      'Final weighted risk': t.finalWeightedRisk || 'الخطر النهائي المرجح',
      'Final risk': t.finalRisk || 'الخطر النهائي',

      'Child sex: female': `${t.childSex || 'جنس الطفل'}: ${t.female || 'أنثى'}`,
      'Child sex: male': `${t.childSex || 'جنس الطفل'}: ${t.male || 'ذكر'}`,
      'Ethnicity: white-european': `${t.ethnicity || 'العرق'}: ${t.whiteEuropean || 'أبيض-أوروبي'}`,
      'Ethnicity: asian': `${t.ethnicity || 'العرق'}: ${t.asian || 'آسيوي'}`,
      'Ethnicity: middle eastern': `${t.ethnicity || 'العرق'}: ${t.middleEastern || 'شرق أوسطي'}`,
      'Ethnicity: black': `${t.ethnicity || 'العرق'}: ${t.black || 'أسود'}`,
      'Ethnicity: south asian': `${t.ethnicity || 'العرق'}: ${t.southAsian || 'جنوب آسيوي'}`,
      'Ethnicity: hispanic': `${t.ethnicity || 'العرق'}: ${t.hispanic || 'من أصل إسباني'}`,
      'Ethnicity: latino': `${t.ethnicity || 'العرق'}: ${t.latino || 'لاتيني'}`,
      'Ethnicity: others': `${t.ethnicity || 'العرق'}: ${t.others || 'أخرى'}`,
      'Ethnicity: mixed': `${t.ethnicity || 'العرق'}: ${t.mixed || 'مختلط'}`,
      'Ethnicity: pacifica': `${t.ethnicity || 'العرق'}: ${t.pacifica || 'جزر المحيط الهادئ'}`,
      'Ethnicity: native indian': `${t.ethnicity || 'العرق'}: ${t.nativeIndian || 'هندي أصلي'}`,
      'Jaundice history: no': `${t.jaundiceHistory || 'تاريخ اليرقان'}: ${t.no || 'لا'}`,
      'Jaundice history: yes': `${t.jaundiceHistory || 'تاريخ اليرقان'}: ${t.yes || 'نعم'}`,
      'Family ASD history: no': `${t.familyASDHistory || 'تاريخ العائلة مع التوحد'}: ${t.no || 'لا'}`,
      'Family ASD history: yes': `${t.familyASDHistory || 'تاريخ العائلة مع التوحد'}: ${t.yes || 'نعم'}`,
      'Note: This report is a screening aid and does not replace a clinical diagnosis.': 'ملاحظة: هذا التقرير هو أداة فحص مساعدة ولا يحل محل التشخيص السريري.',

      'Does your child look at you when you call his/her name?': t.q1,
      'How easy is it for you to get eye contact with your child?': t.q2,
      'Does your child point to indicate that s/he wants something?': t.q3,
      'Does your child point to indicate that s/he wants something? (e.g., a toy that is out of reach)': t.q3,
      'Does your child point to share interest with you?': t.q4,
      'Does your child point to share interest with you? (e.g., pointing at an interesting sight)': t.q4,
      'Does your child pretend?': t.q5,
      'Does your child pretend? (e.g., care for dolls, talk on a toy phone)': t.q5,
      'Does your child follow where you’re looking?': t.q6,
      'If you or someone else is upset, does your child seem to notice or care?': t.q7,
      'If someone is upset, does your child try to comfort them?': t.q7,
      'Would you describe your child’s first words as:': t.q8,
      'Does your child make unusual finger movements near his/her eyes?': t.q9,
      'Does your child use simple gestures?': t.q9,
      'Does your child become fascinated by moving objects? (e.g., wheels, spinning objects)': t.q10,
      'Does your child stare at nothing with no apparent purpose?': t.q10,

      'Always': t.always,
      'Usually': t.usually,
      'Sometimes': t.sometimes,
      'Rarely': t.rarely,
      'Never': t.never,
      'Very easy': t.veryEasy,
      'Quite easy': t.quiteEasy,
      'Quite difficult': t.quiteDifficult,
      'Very difficult': t.veryDifficult,
      'Impossible': t.impossible,
      'Many times a day': t.manyTimesDay,
      'Few times a day': t.fewTimesDay,
      'Few times a week': t.fewTimesWeek,
      'Less than once a week': t.lessThanOnceWeek,
      'Very typical': t.veryTypical,
      'Quite typical': t.quiteTypical,
      'Slightly unusual': t.slightlyUnusual,
      'Very unusual': t.veryUnusual,
      "Doesn't speak": t.doesntSpeak
    };

    const sortedKeys = Object.keys(allMaps).sort((a, b) => b.length - a.length);

    for (const eng of sortedKeys) {
      if (allMaps[eng]) {
        const isSingleWord = !eng.includes(' ');
        const regexStr = isSingleWord 
          ? `\\b${eng.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b` 
          : eng.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        
        const regex = new RegExp(regexStr, 'gi');
        translated = translated.replace(regex, allMaps[eng]);
      }
    }

    return translated;
  };

  const getArabicRiskLabel = (englishLabel) => {
    if (!englishLabel) return englishLabel;
    const label = englishLabel.toLowerCase();
    if (label.includes('high risk')) return t.highRiskAr || 'خطر مرتفع';
    if (label.includes('low risk')) return t.lowRiskAr || 'خطر منخفض';
    if (label.includes('moderate risk')) return t.moderateRiskAr || 'خطر متوسط';
    if (label.includes('no autism likelihood detected')) return t.noAutismLikelihoodDetected || 'لم يتم اكتشاف احتمالية التوحد';
    if (label.includes('low autism likelihood')) return t.lowAutismLikelihood || 'احتمالية توحد منخفضة';
    if (label.includes('autism likelihood detected')) return t.autismLikelihoodDetected || 'تم اكتشاف احتمالية التوحد';
    if (label.includes('final risk')) return t.finalRiskAr || 'الخطر النهائي';
    return englishLabel;
  };

  const getTranslatedCaseResult = (resultSummary) => {
    if (language !== 'ar') return resultSummary;
    if (!resultSummary) return t.noReportYet || '';

    let translated = String(resultSummary);
    
    const phrases = {
      'no autism likelihood detected': t.noAutismLikelihoodDetected || 'لم يتم اكتشاف احتمالية التوحد',
      'low autism likelihood': t.lowAutismLikelihood || 'احتمالية توحد منخفضة',
      'autism likelihood detected': t.autismLikelihoodDetected || 'تم اكتشاف احتمالية التوحد',
      'high risk': t.highRiskAr || 'خطر مرتفع',
      'low risk': t.lowRiskAr || 'خطر منخفض',
      'moderate risk': t.moderateRiskAr || 'خطر متوسط',
      'q-chat risk': t.qchatRisk || 'خطر Q-CHAT',
      'facial image risk': t.facialImageRisk || 'خطر صورة الوجه',
      'facial risk': t.facialRisk || 'خطر الوجه',
      'final weighted risk': t.finalWeightedRisk || 'الخطر النهائي المرجح',
      'final risk': t.finalRisk || 'الخطر النهائي'
    };

    const sortedPhrases = Object.keys(phrases).sort((a, b) => b.length - a.length);
    
    sortedPhrases.forEach(eng => {
      const regex = new RegExp(eng, 'gi');
      translated = translated.replace(regex, phrases[eng]);
    });

    return translated;
  };

  async function loadCases() {
    const data = await api('/cases');
    setCases(data.cases || []);
  }

  useEffect(() => { loadCases(); }, []);

  useEffect(() => {
    if (message) {
      const timer = setTimeout(() => setMessage(''), 3000);
      return () => clearTimeout(timer);
    }
  }, [message]);

  function setAnswer(name, value) {
    setQchat((prev) => ({ ...prev, [name]: value }));
  }

  function handleImageChange(e) {
    const file = e.target.files?.[0];
    if (!file) return;
    setFaceImage(file);
    setImageChecked(false);
    setError('');
    if (imagePreview) URL.revokeObjectURL(imagePreview);
    setImagePreview(URL.createObjectURL(file));
  }

  async function validateFaceAndContinue() {
    try {
      setError('');
      if (!faceImage) {
        setError(t.pleaseUploadImage);
        return;
      }
      const formData = new FormData();
      formData.append('image', faceImage);
      formData.append('case_id', activeCase.id);
      const data = await api('/validate-face-image', {
        method: 'POST',
        body: formData,
        isFormData: true
      });
      if (!data.valid) {
        setError(data.error || t.clearFrontFaceImage);
        return;
      }
      setImageChecked(true);
      setAssessmentStep('questions');
    } catch (err) {
      setError(err.message || t.imageValidationFailed);
    }
  }

  async function createCase() {
    try {
      const data = await api('/cases', {
        method: 'POST',
        body: JSON.stringify(form)
      });
      setCases([data.case, ...cases]);
      setForm(emptyForm);
      setMessage(t.caseCreated);
      setError('');
      setView('list');
    } catch (err) {
      setError(err.message);
    }
  }

  async function deleteCase(id) {
    if (!window.confirm(t.deleteCaseConfirm)) return;
    await api(`/cases/${id}`, { method: 'DELETE' });
    setCases(cases.filter((c) => c.id !== id));
  }

  async function openReports(caseItem) {
    setActiveCase(caseItem);
    const data = await api(`/cases/${caseItem.id}/reports`);
    setReports(data.reports || []);
    try {
      const gameData = await api(`/cases/${caseItem.id}/game-scores`);
      setGameScores(gameData.game_scores || []);
    } catch {
      setGameScores([]);
    }
    setView('reports');
  }

  const GAME_LABELS = {
    recognition: t.gameIntroTitle,
    shapes: t.shapeGameTitle,
    emotions: t.emotionGameTitle,
  };

  async function submitTest() {
    try {
      setError('');
      if (!faceImage) {
        setError(t.pleaseUploadImage);
        return;
      }
      for (let i = 1; i <= 10; i++) {
        if (!qchat[`A${i}`]) {
          setError(t.pleaseAnswerQuestion.replace('{i}', i));
          return;
        }
      }
      if (!qchat.child_sex || !qchat.child_ethnicity || !qchat.jaundice || !qchat.family_asd) {
        setError(t.fillAllInputs);
        return;
      }
      const formData = new FormData();
      Object.entries(qchat).forEach(([key, value]) => formData.append(key, value));
      formData.append('image', faceImage);
      const data = await api(`/cases/${activeCase.id}/test`, {
        method: 'POST',
        body: formData,
        isFormData: true
      });
      
      setCurrentReport(data.result);
      await loadCases();
      setView('report');
    } catch (err) {
      setError(err.message);
    }
  }

  const riskPercent = useMemo(() => {
    return currentReport?.combined_risk != null
      ? `${(currentReport.combined_risk * 100).toFixed(1)}%`
      : t.notApplicable || 'N/A';
  }, [currentReport, t]);

  const generatePDF = () => {
    if (!currentReport) return;

    const isArabic = language === 'ar';
    const isHighRisk = currentReport.prediction_label?.toLowerCase().includes('high') || 
                       currentReport.prediction_label?.toLowerCase().includes('autism likelihood detected');
    
    // SPLIT THE VARIABLES HERE: 
    // Solid colors for borders/text. Gradient for backgrounds only.
    const themeColorSolid = isHighRisk ? '#dc2626' : '#059669';
    const themeBgGradient = isHighRisk 
      ? 'linear-gradient(135deg, #ff0000 0%, #7a1010 100%)' 
      : 'linear-gradient(135deg, #4ce3ac 0%, #058059 100%)'; 

    const themeBg = isHighRisk ? '#fef2f2' : '#ecfdf5';    
    // eslint-disable-next-line no-unused-vars
    const themeBorder = isHighRisk ? '#fca5a5' : '#6ee7b7';
    
    const riskLabelEn = isHighRisk ? "HIGH RISK" : "LOW RISK";
    const riskLabelAr = isHighRisk ? "خطر مرتفع" : "خطر منخفض";
    const displayRiskLabel = isArabic ? riskLabelAr : riskLabelEn;
    
    const dateStr = new Date(currentReport.created_at).toLocaleDateString(isArabic ? 'ar-EG' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    const displayText = isArabic ? translateReportToArabic(currentReport.report_text) : (currentReport.report_text || '');

    // Safely extract demographics from the stored report text
    const extractDemo = (text, key) => {
      if (!text) return null;
      const regex = new RegExp(`${key}:\\s*([^\\n\\r]+)`, 'i');
      const match = text.match(regex);
      return match ? match[1].trim() : null;
    };

    const demSex = extractDemo(currentReport.report_text, 'Child sex') || qchat.child_sex || 'N/A';
    const demEthnicity = extractDemo(currentReport.report_text, 'Ethnicity') || qchat.child_ethnicity || 'N/A';
    const demJaundice = extractDemo(currentReport.report_text, 'Jaundice history') || qchat.jaundice || 'N/A';
    const demFamilyAsd = extractDemo(currentReport.report_text, 'Family ASD history') || qchat.family_asd || 'N/A';

    const tr = (eng, ar, translationKey) => {
        if (isArabic) return t[translationKey] || ar;
        return t[translationKey] || eng;
    };

    const translateVal = (val) => {
        if (!val || val === 'N/A') return 'N/A';
        if (!isArabic) {
            return String(val).charAt(0).toUpperCase() + String(val).slice(1);
        }
        const v = String(val).toLowerCase().trim();
        const map = {
            'male': t.male || 'ذكر',
            'female': t.female || 'أنثى',
            'yes': t.yes || 'نعم',
            'no': t.no || 'لا',
            'white-european': t.whiteEuropean || 'أبيض-أوروبي',
            'asian': t.asian || 'آسيوي',
            'middle eastern': t.middleEastern || 'شرق أوسطي',
            'black': t.black || 'أسود',
            'south asian': t.southAsian || 'جنوب آسيوي',
            'hispanic': t.hispanic || 'من أصل إسباني',
            'latino': t.latino || 'لاتيني',
            'others': t.others || 'أخرى',
            'mixed': t.mixed || 'مختلط',
            'pacifica': t.pacifica || 'جزر المحيط الهادئ',
            'native indian': t.nativeIndian || 'هندي أصلي'
        };
        return map[v] || val;
    };

    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert(t.allowPopups || "Please allow popups to generate the PDF.");
      return;
    }

    const htmlContent = `
      <!DOCTYPE html>
      <html lang="${isArabic ? 'ar' : 'en'}" dir="${isArabic ? 'rtl' : 'ltr'}">
      <head>
        <meta charset="UTF-8">
        <title>Auto-Ism Report - ${activeCase?.child_name || ''}</title>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;800&display=swap');
          
          @page { size: A4; margin: 0; }
          body { 
            font-family: 'Cairo', sans-serif; 
            margin: 0; 
            background: #e2e8f0; 
            -webkit-print-color-adjust: exact; 
            print-color-adjust: exact; 
          }
          
          .page {
            width: 210mm;
            min-height: 297mm;
            padding: 20mm;
            margin: 0 auto;
            background: white;
            box-sizing: border-box;
            position: relative;
            page-break-after: always;
          }
          .page:last-child { page-break-after: auto; }

          .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 3px solid ${themeColorSolid}; /* FIXED: Using solid color for border */
            padding-bottom: 15px;
            margin-bottom: 30px;
          }
          .header-left h1 { margin: 0; font-size: 32px; color: #0f172a; font-weight: 800; letter-spacing: -1px; }
          .header-left p { margin: 5px 0 0; color: #64748b; font-size: 14px; }
          .header-right { text-align: ${isArabic ? 'left' : 'right'}; font-size: 12px; color: #94a3b8; line-height: 1.5; }

          .patient-card {
            border: 1px solid #cbd5e1;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 30px;
            background-color: #f8fafc;
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
          }
          .info-block { display: flex; flex-direction: column; }
          .info-label { font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #64748b; font-weight: 600; margin-bottom: 4px; }
          .info-value { font-size: 16px; color: #0f172a; font-weight: 600; }

          .risk-banner {
            background: ${themeBgGradient}; /* FIXED: Using gradient exclusively for background */
            color: white !important;
            padding: 25px;
            border-radius: 8px;
            text-align: center;
            margin-bottom: 30px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
          }
          .risk-title { font-size: 14px; text-transform: uppercase; letter-spacing: 2px; opacity: 0.9; margin-bottom: 5px; }
          .risk-status { font-size: 32px; font-weight: 800; letter-spacing: 1px; margin: 0; }

          h2.section-title { font-size: 20px; color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; margin-bottom: 20px; }
          
          table { width: 100%; border-collapse: collapse; margin-bottom: 30px; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.05); border: 1px solid #cbd5e1; }
          th, td { padding: 16px; text-align: start; border-bottom: 1px solid #e2e8f0; }
          th { background-color: #f1f5f9; color: #475569; font-weight: 600; font-size: 14px; text-transform: uppercase; }
          td { color: #334155; font-size: 15px; }
          tr:last-child td { border-bottom: none; }
          
          .highlight-row { background-color: ${themeBg}; }
          .highlight-row td { color: ${themeColorSolid}; font-weight: 800; font-size: 18px; } /* FIXED: Solid color for text */

          .analysis-text {
            line-height: 1.8;
            font-size: 15px;
            color: #334155;
            background: #fff;
            padding: 20px;
            border-left: ${isArabic ? 'none' : `4px solid ${themeColorSolid}`}; /* FIXED: Solid color for border */
            border-right: ${isArabic ? `4px solid ${themeColorSolid}` : 'none'}; /* FIXED: Solid color for border */
            border-radius: ${isArabic ? '8px 0 0 8px' : '0 8px 8px 0'};
            box-shadow: 0 1px 3px rgba(0,0,0,0.05);
            white-space: pre-wrap;
          }

          .footer {
            position: absolute;
            bottom: 20mm;
            left: 20mm;
            right: 20mm;
            border-top: 1px solid #cbd5e1;
            padding-top: 15px;
            font-size: 11px;
            color: #94a3b8;
            text-align: justify;
            line-height: 1.5;
          }
          .footer-date { text-align: center; margin-top: 10px; font-weight: 600; }
          
          @media print { body { background: white; } .page { box-shadow: none; margin: 0; } }
        </style>
      </head>
      <body>

        <div class="page">
          <div class="header">
            <div class="header-left">
              <h1>Auto-Ism</h1>
              <p>${tr('Early Autism Screening Report', 'تقرير الفحص المبكر للتوحد', 'pdfTitle')}</p>
            </div>
            <div class="header-right">
              ${tr('Cairo University FCAI 2026', 'جامعة القاهرة - كلية الحاسبات والذكاء الاصطناعي 2026', 'cairoUniv')}<br>
              ${tr('Supervised by Dr. Elham Shawky', 'إشراف د. إلهام شوقي', 'supervisedBy')}
            </div>
          </div>

          <div class="patient-card">
            <div class="info-block">
              <span class="info-label">${tr('Patient Name', 'اسم المريض', 'childName')}</span>
              <span class="info-value">${activeCase?.child_name || 'N/A'}</span>
            </div>
            <div class="info-block">
              <span class="info-label">${tr('Date of Assessment', 'تاريخ التقييم', 'date')}</span>
              <span class="info-value">${dateStr}</span>
            </div>
            <div class="info-block">
              <span class="info-label">${tr('DOB', 'تاريخ الميلاد', 'dob')}</span>
              <span class="info-value">${activeCase?.child_dob || 'N/A'}</span>
            </div>
            <div class="info-block">
              <span class="info-label">${tr('Case Reference', 'رقم الحالة', 'caseId')}</span>
              <span class="info-value">#${currentReport.case_id}</span>
            </div>
          </div>

          <div class="risk-banner">
            <div class="risk-title">${tr('Combined Risk Indication', 'مؤشر المخاطر المجمعة', 'combinedRisk')}</div>
            <div class="risk-status">${displayRiskLabel}</div>
          </div>

          <h2 class="section-title">${tr('Model Diagnostics', 'تشخيصات النموذج', 'modelDiagnostics')}</h2>
          <table>
            <thead>
              <tr>
                <th>${tr('Assessment Component', 'مكون التقييم', 'assessmentComponent')}</th>
                <th>${tr('Calculated Score', 'الدرجة المحسوبة', 'calculatedScore')}</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>${tr('Q-CHAT-10 Questionnaire Analysis', 'تحليل استبيان Q-CHAT-10', 'qchatAnalysis')}</td>
                <td>${currentReport.spark_score}/10</td>
              </tr>
              <tr>
                <td>${tr('Facial Biometric Analysis', 'التحليل البيومتري للوجه', 'facialAnalysis')}</td>
                <td>${currentReport.image_score != null ? (currentReport.image_score * 100).toFixed(1) + '%' : 'N/A'}</td>
              </tr>
              <tr class="highlight-row">
                <td>${tr('Final Weighted Probability', 'الاحتمالية النهائية المرجحة', 'finalWeightedProb')}</td>
                <td>${riskPercent}</td>
              </tr>
            </tbody>
          </table>
          
          <div class="footer">
            ${isArabic
              ? "هذا التقرير هو أداة مساعدة قائمة على الذكاء الاصطناعي ولا يشكل تشخيصاً طبياً رسمياً. صُمم Auto-Ism لدعم المتخصصين وليس لاستبدالهم. يجب عرض هذه النتائج على طبيب أطفال أو أخصائي توحد معتمد."
              : "This report is generated by an AI-based screening tool and does NOT constitute a medical diagnosis. Auto-Ism is a decision-support system. Results must be interpreted by a qualified healthcare professional. Consult a pediatrician for formal evaluation."}
          </div>
        </div>

        <div class="page">
          <div class="header">
            <div class="header-left">
              <h1>Auto-Ism</h1>
              <p>${tr('Detailed Analysis & Demographics', 'التحليل المفصل والبيانات الديموغرافية', 'detailedAnalysis')}</p>
            </div>
          </div>

          <h2 class="section-title">${tr('Demographic Profile', 'الملف الديموغرافي', 'demographicProfile')}</h2>
          <table>
            <tbody>
              <tr>
                <td style="width: 50%; font-weight: 600; color: #64748b;">${tr('Biological Sex', 'الجنس البيولوجي', 'bioSex')}</td>
                <td>${translateVal(demSex)}</td>
              </tr>
              <tr>
                <td style="font-weight: 600; color: #64748b;">${tr('Ethnicity', 'العرق', 'ethnicity')}</td>
                <td>${translateVal(demEthnicity)}</td>
              </tr>
              <tr>
                <td style="font-weight: 600; color: #64748b;">${tr('History of Jaundice', 'تاريخ الإصابة باليرقان', 'historyJaundice')}</td>
                <td>${translateVal(demJaundice)}</td>
              </tr>
              <tr>
                <td style="font-weight: 600; color: #64748b;">${tr('Family ASD History', 'تاريخ العائلة مع التوحد', 'familyASDHistory')}</td>
                <td>${translateVal(demFamilyAsd)}</td>
              </tr>
            </tbody>
          </table>

          <h2 class="section-title">${tr('Clinical Recommendation', 'التوصية السريرية', 'assessmentResults')}</h2>
          <div class="analysis-text">${displayText}</div>

          <div class="footer">
             <div class="footer-date">${tr('Generated', 'تم الإنشاء بواسطة', 'generatedBy')}: ${dateStr}</div>
          </div>
        </div>

        <script>
          window.onload = () => {
            setTimeout(() => {
              window.print();
              window.onafterprint = () => window.close(); 
            }, 500);
          };
        </script>
      </body>
      </html>
    `;
    printWindow.document.open();
    printWindow.document.write(htmlContent);
    printWindow.document.close();
  };

  const displayedCases = cases.slice(0, displayCount);
  const showingAllCases = displayCount >= cases.length && cases.length > 6;
  const toggleCaseDisplay = () => {
    if (showingAllCases) setDisplayCount(6);
    else setDisplayCount(prev => Math.min(prev + 6, cases.length));
  };

  return (
    <div className="cases-page" dir={language === 'ar' ? 'rtl' : 'ltr'}>
      <div className="container">
        {error && <div className="error-message">{error}</div>}
        {message && <div className="success-message">{message}</div>}

        {view === 'list' && (
          <div>
            <div className="list-header">
              <h2>{t.myCases}</h2>
              <button className="btn btn-primary" onClick={() => setView('create')}>
                <FontAwesomeIcon icon={faPlus} /> {t.createNewCase}
              </button>
            </div>
            {cases.length === 0 ? (
              <div className="empty-state">
                <FontAwesomeIcon icon={faFileMedical} />
                <h3>{t.noCasesYet}</h3>
                <p>{t.createFirstCase}</p>
              </div>
            ) : (
              <>
                <div className="cases-grid">
                  {displayedCases.map(item => (
                    <div key={item.id} className="case-card">
                      <div className="case-card-content">
                        <div className="case-info">
                          <h3>{item.child_name}</h3>
                          <p className="case-dob">{t.dob}: {item.child_dob}</p>
                          {item.brief && <p className="case-brief">{item.brief}</p>}
                          <p className="case-result" dir="auto" style={{lineHeight: '1.6'}}>{getTranslatedCaseResult(item.last_result_summary) || t.noReportYet}</p>
                        </div>
                        <div className="case-actions">
                          <button className="btn btn-primary" onClick={() => {
                            setActiveCase(item);
                            setQchat(emptyQchat);
                            setFaceImage(null);
                            setImageChecked(false);
                            setAssessmentStep('image');
                            setError('');
                            if (imagePreview) URL.revokeObjectURL(imagePreview);
                            setImagePreview('');
                            setView('assessment');
                          }}>
                            <FontAwesomeIcon icon={faPlay} /> {t.test}
                          </button>
                          <button className="btn btn-secondary" onClick={() => openReports(item)}>
                            <FontAwesomeIcon icon={faList} /> {t.reports}
                          </button>
                          <button className="btn btn-danger" onClick={() => deleteCase(item.id)}>
                            <FontAwesomeIcon icon={faTrash} /> {t.delete}
                          </button>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
                {cases.length > 6 && (
                  <div className="load-more-container">
                    <button onClick={toggleCaseDisplay} className="btn btn-secondary load-more-btn">
                      <FontAwesomeIcon icon={showingAllCases ? faChevronUp : faChevronDown} />
                      {showingAllCases ? t.showLess : `${t.loadMore} (${cases.length - displayCount} ${t.remaining})`}
                    </button>
                  </div>
                )}
              </>
            )}
          </div>
        )}

        {view === 'create' && (
          <div className="form-container">
            <h2>{t.createNewCase}</h2>
            <div className="form-group">
              <label>{t.childName}</label>
              <input type="text" className="form-control" value={form.child_name} onChange={e => setForm({...form, child_name: e.target.value})} required />
            </div>
            <div className="form-group">
              <label>{t.dateOfBirth}</label>
              <input type="date" className="form-control" value={form.child_dob} onChange={e => setForm({...form, child_dob: e.target.value})} required />
            </div>
            <div className="form-group">
              <label>{t.briefNotes} <span style={{color:'var(--text-muted)', fontSize:'0.85rem'}}>({t.optional})</span></label>
              <textarea className="form-control" rows="4" value={form.brief} onChange={e => setForm({...form, brief: e.target.value})} />
            </div>
            <div className="form-actions">
              <button className="btn btn-secondary" onClick={() => setView('list')}>{t.cancel}</button>
              <button className="btn btn-primary" onClick={createCase}>{t.createCase}</button>
            </div>
          </div>
        )}

        {view === 'assessment' && activeCase && (
          <div>
            <button className="back-button" onClick={() => setView('list')}><FontAwesomeIcon icon={faArrowLeft} /> {t.backToCases}</button>
            <div className="form-container">
              <h2>{t.finalAssessment} {activeCase.child_name}</h2>
              {assessmentStep === 'image' && (
                <>
                  <div className="instructions-box"><h3>{t.photoInstructions}</h3><ul><li>{t.instruction1}</li><li>{t.instruction2}</li><li>{t.instruction3}</li><li>{t.instruction4}</li><li>{t.instruction5}</li><li>{t.instruction6}</li></ul></div>
                  <div className="form-group"><label>{t.uploadImage}</label><input type="file" accept="image/*" className="form-control" onChange={handleImageChange} /></div>
                  {imagePreview && <div className="image-preview"><img src={imagePreview} alt={t.preview} /></div>}
                  <button className="btn btn-primary" onClick={validateFaceAndContinue}>{t.continueToQuestions}</button>
                </>
              )}
              {assessmentStep === 'questions' && (
                <>
                  <div style={{ textAlign: 'center', marginBottom: '1.5rem' }}>
                    <img src={mascotThinking} alt="mascot thinking" style={{ width: '120px', objectFit: 'contain', filter: 'drop-shadow(0 6px 16px rgba(56,189,248,0.3))', animation: 'mascotFloat 4s ease-in-out infinite' }} />
                  </div>
                  <div className={`status-box ${imageChecked ? 'accepted' : ''}`}>{imageChecked ? t.imageAccepted : t.completeQuestions}</div>
                  <div className="form-group"><label>{t.childSex}</label><select className="form-control" value={qchat.child_sex} onChange={e => setAnswer('child_sex', e.target.value)}><option value="">{t.selectSex}</option><option value="male">{t.male}</option><option value="female">{t.female}</option></select></div>
                  <div className="form-group"><label>{t.ethnicity}</label><select className="form-control" value={qchat.child_ethnicity} onChange={e => setAnswer('child_ethnicity', e.target.value)}><option value="">{t.selectEthnicity}</option><option value="white-european">{t.whiteEuropean}</option><option value="asian">{t.asian}</option><option value="middle eastern">{t.middleEastern}</option><option value="black">{t.black}</option><option value="south asian">{t.southAsian}</option><option value="hispanic">{t.hispanic}</option><option value="latino">{t.latino}</option><option value="others">{t.others}</option><option value="mixed">{t.mixed}</option><option value="pacifica">{t.pacifica}</option><option value="native indian">{t.nativeIndian}</option></select></div>
                  <div className="form-group"><label>{t.jaundiceHistory}</label><select className="form-control" value={qchat.jaundice} onChange={e => setAnswer('jaundice', e.target.value)}><option value="">{t.selectOption}</option><option value="no">{t.no}</option><option value="yes">{t.yes}</option></select></div>
                  <div className="form-group"><label>{t.familyASDHistory}</label><select className="form-control" value={qchat.family_asd} onChange={e => setAnswer('family_asd', e.target.value)}><option value="">{t.selectOption}</option><option value="no">{t.no}</option><option value="yes">{t.yes}</option></select></div>
                  {[1,2,3,4,5,6,7,8,9,10].map(i => (
                    <div className="question-group" key={i}>
                      <label>Q{i}. {questionTexts[i]}</label>
                      <div className="options-grid">
                        {answerLetters.map((letter, idx) => (
                          <label key={letter} className={`option-label ${qchat[`A${i}`] === letter ? 'selected' : ''}`}>
                            <input type="radio" name={`A${i}`} value={letter} checked={qchat[`A${i}`] === letter} onChange={e => setAnswer(`A${i}`, e.target.value)} />
                            <span><strong>{letter}</strong> — {options[i][idx]}</span>
                          </label>
                        ))}
                      </div>
                    </div>
                  ))}
                  <button className="btn btn-primary" onClick={submitTest}>{t.runFinalAssessment}</button>
                </>
              )}
            </div>
          </div>
        )}

        {view === 'report' && currentReport && (
          <div className="report-container">
            <button className="back-button" onClick={() => setView('list')}><FontAwesomeIcon icon={faArrowLeft} /> {t.backToCases}</button>
            <div className="report-header">
              {!(currentReport.prediction_label?.toLowerCase().includes('high') || currentReport.prediction_label?.toLowerCase().includes('autism likelihood detected')) && (
                <img src={mascotHappyResult} alt="mascot" style={{ width: '110px', objectFit: 'contain', filter: 'drop-shadow(0 6px 20px rgba(56,189,248,0.35))', animation: 'mascotFloat 4s ease-in-out infinite', marginBottom: '0.5rem' }} />
              )}
              <div className="score-circle">{riskPercent}</div>
              <h2>{language === 'ar' ? getArabicRiskLabel(currentReport.prediction_label) : currentReport.prediction_label}</h2>
            </div>
            <div className="report-body">
              <div className="report-stats">
                <div className="stat-item"><p>{t.qchatScore || 'Q-CHAT Score'}</p><h3>{currentReport.spark_score}/10</h3></div>
                <div className="stat-item"><p>{t.facialRisk || 'Facial risk'}</p><h3>{currentReport.image_score != null ? `${(currentReport.image_score * 100).toFixed(1)}%` : (t.notApplicable || 'N/A')}</h3></div>
                <div className="stat-item"><p>{t.combinedRisk || 'Combined Risk'}</p><h3>{riskPercent}</h3></div>
              </div>
              <div className="report-text" dir="auto">
                {language === 'ar' ? translateReportToArabic(currentReport.report_text) : currentReport.report_text}
              </div>
              <button className="btn btn-primary" onClick={generatePDF}><FontAwesomeIcon icon={faDownload} /> {t.downloadPDF}</button>
            </div>
          </div>
        )}

        {view === 'reports' && activeCase && (
          <div>
            <button className="back-button" onClick={() => setView('list')}><FontAwesomeIcon icon={faArrowLeft} /> {t.backToCases}</button>
            <h2>{t.reportsFor} {activeCase.child_name}</h2>

            {gameScores.length > 0 && (
              <div className="game-scores-panel">
                <h3>{t.playAndLearn} {t.score}</h3>
                <div className="game-scores-grid">
                  {gameScores.map((gs) => (
                    <div key={gs.id} className="game-score-card">
                      <p className="game-score-name">{GAME_LABELS[gs.game] || gs.game}</p>
                      <p className="game-score-value">{gs.score}/{gs.max_score}</p>
                      {gs.level && <p className="game-score-level">{t[gs.level] || gs.level}</p>}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {reports.length === 0 ? (
              <p>{t.noReportsYet}</p>
            ) : (
              <div className="reports-list">
                {reports.map(r => {
                  const displayLabel = language === 'ar' ? getArabicRiskLabel(r.prediction_label) : r.prediction_label;
                  const displayNotes = getTranslatedCaseResult(r.notes);
                  return (
                    <div key={r.id} className="report-item">
                      <h3>{displayLabel}</h3>
                      <p className="report-date">{new Date(r.created_at).toLocaleString(language === 'ar' ? 'ar-EG' : 'en-US')}</p>
                      <p className="report-notes" dir="auto" style={{lineHeight: '1.6'}}>{displayNotes}</p>
                      <button className="btn btn-primary" onClick={() => {
                        setCurrentReport(r);
                        setView('report');
                      }}>{t.openReport}</button>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default Cases;